# Generated by Django 2.0.3 on 2018-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcar',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='购买数量'),
        ),
    ]
