# Generated by Django 2.0.3 on 2018-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodscategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='category_name',
        ),
        migrations.AddField(
            model_name='goods',
            name='category_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
