# Generated by Django 2.0.3 on 2018-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d'),
        ),
    ]
