# Generated by Django 2.0.3 on 2018-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', help_text='留言内容', verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], help_text='留言类型:1(留言),2(投诉),3(询问),4(售后),5(求购)', verbose_name='留言类型'),
        ),
    ]
