# Generated by Django 2.0.3 on 2018-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC', '0003_auto_20180328_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='invite_reasone',
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
