# Generated by Django 2.0.3 on 2018-04-13 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC', '0004_auto_20180328_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 4, 13, 22, 46, 51, 332312), verbose_name='时间')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('image', models.ImageField(upload_to='static/images/%Y/%m/%d', verbose_name='图片')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='作者')),
                ('status', models.IntegerField(choices=[(0, '进行中'), (1, '已完成')], default=0, verbose_name='状态')),
            ],
            options={
                'db_table': 'uploadedimage',
            },
        ),
    ]
