# Generated by Django 2.0.3 on 2018-04-15 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETC', '0006_auto_20180414_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimagemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 15, 46, 11, 689354), verbose_name='时间'),
        ),
    ]
